# Generated by Django 4.1.3 on 2022-11-30 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('apart_type', models.CharField(max_length=50, verbose_name='type')),
                ('description', models.TextField(verbose_name='description')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='size')),
                ('room', models.IntegerField(verbose_name='room(s)')),
                ('bed', models.IntegerField(verbose_name='bed(s)')),
                ('sofa', models.IntegerField(null=True, verbose_name='sofa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reserved', models.DateField(auto_now_add=True, verbose_name='date of reservation')),
                ('date_in', models.DateField(blank=True, null=True, verbose_name='date in')),
                ('date_out', models.DateField(blank=True, null=True, verbose_name='date out')),
                ('status', models.CharField(choices=[('r', 'reserved'), ('c', 'canceled'), ('a', 'available'), ('p', 'past'), ('n', 'no info')], default='n', max_length=1, verbose_name='status')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='apartments.apartment', verbose_name='apartment')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='apartments.guest', verbose_name='guest')),
            ],
        ),
    ]
