# Generated by Django 4.1.3 on 2022-12-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartment_photo_2_apartment_photo_3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date_in']},
        ),
        migrations.CreateModel(
            name='ApartmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='photo_1')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='photo_2')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='photo_3')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='apartments.apartment', verbose_name='Apartment')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_reviews', to='apartments.guest', verbose_name='Guest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
