# Generated by Django 4.1.3 on 2022-12-09 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartments', '0006_alter_reservation_options_apartmentreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentreview',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Guest'),
        ),
    ]
